<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-9QFBHCIE" name="Amazon App Test" tests="1" failures="1" timestamp="10 Jul 2020 16:13:32 GMT" time="141.251" errors="0">
  <testcase name="TestCaseController" time="124.509" classname="runner.TestController">
    <failure type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at runner.TestController.TestCaseController(TestController.java:79)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at keyWords.Keywords.getLocator(Keywords.java:180)
	at keyWords.Keywords.getElement(Keywords.java:170)
	at keyWords.Keywords.checkoutPage(Keywords.java:61)
	... 33 more
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- TestCaseController -->
</testsuite> <!-- Amazon App Test -->
